import assert from "node:assert/strict";
const {selectSaveUser,receiveSavePrompt,promptTargetSave} = await import(`data:text/javascript;base64,${process.env.RSA_SAVE_PROMPT_SOURCE}`);
const gm={id:"gm",active:true,isGM:true},main={id:"main",active:true,isGM:false,character:{id:"actor"}},
    alternate={id:"alternate",active:true,isGM:false},caster={id:"caster",active:true,isGM:false};
const users=[gm,alternate,main,caster];
users.activeGM=gm;users.get=id=>users.find(user=>user.id===id);
let calls=[];
const actor={id:"actor",isOwner:true,testUserPermission:user=>["main","alternate"].includes(user.id),
    async rollSavingThrow(config,dialog,message){calls.push({config,dialog,message});return [];} };
const token={uuid:"Scene.scene.Token.target",actor,parent:{id:"scene"}};
const activity={type:"save",save:{ability:new Set(["wis"]),dc:{value:15},bonus:"1"},
    getRollData:()=>({}),messageSources:{activity:{uuid:"Actor.caster.Item.spell.Activity.save"}}};
const message={id:"usage",author:caster,system:{targets:[{token:token.uuid}]},getAssociatedActivity:()=>activity};
const messages=new Map([[message.id,message]]);
let packets=[];
let worldEnabled=true;
globalThis.game={users,user:main,messages,settings:{get:()=>worldEnabled},socket:{emit:(channel,packet)=>packets.push(packet)}};
globalThis.fromUuid=async uuid=>uuid===token.uuid?token:null;
globalThis.CONFIG={Dice:{BasicRoll:{replaceFormulaData:formula=>formula,constructParts:data=>({parts:["@activityBonus"],data})}}};
globalThis.ChatMessage={getSpeaker:({actor,token})=>({actor:actor.id,token:token.uuid})};
globalThis.ui={notifications:{warn(){},error(message){throw new Error(message);}}};
assert.equal(selectSaveUser(actor,users,gm),main);
const packet={messageId:message.id,tokenUuid:token.uuid,sourceId:caster.id,userId:main.id};
await Promise.all([receiveSavePrompt(packet),receiveSavePrompt(packet)]);
assert.equal(calls.length,1);
assert.equal(calls[0].config.ability,"wis");assert.equal(calls[0].config.target,15);
assert.equal(calls[0].dialog.configure,true);
assert.equal(calls[0].message.data.system.origin,message.id);
assert.equal(calls[0].config.rolls[0].data.activityBonus,"1");
await receiveSavePrompt({...packet,sourceId:alternate.id});
await receiveSavePrompt({...packet,tokenUuid:"Scene.scene.Token.unlisted"});
assert.equal(calls.length,1);
game.user=caster;
worldEnabled=false;
await promptTargetSave(message,token,{promptSavingThrow:false});
assert.equal(packets.length,0);
worldEnabled=true;
await promptTargetSave(message,token,{promptSavingThrow:false});
assert.equal(packets[0].userId,main.id);
assert.equal(packets[0].tokenUuid,token.uuid);
await promptTargetSave(message,token,{promptSavingThrow:true,movementDamage:true});
assert.equal(packets.length,1);
main.active=false;alternate.active=false;
assert.equal(selectSaveUser(actor,users,gm),gm);
game.user=gm;
message.id="npc-usage";messages.set(message.id,message);
await receiveSavePrompt({...packet,messageId:message.id,userId:gm.id});
assert.equal(calls.length,2);
worldEnabled=false;
message.id="disabled-setting";messages.set(message.id,message);
await receiveSavePrompt({...packet,messageId:message.id,userId:gm.id});
assert.equal(calls.length,2,"Disabled world setting prevents receiving a prompt too");
worldEnabled=true;
activity.type="damage";
await promptTargetSave(message,token,{promptSavingThrow:true});
assert.equal(packets.length,1);
console.log("Save prompt checks passed: target-owner routing, one owner, duplicate prevention, native DC/ability/bonus/origin, authorization, GM fallback, opt-in and Save-only behavior.");
